data <- c(122,233,344,455,566,677,788,899,900)
print("Dataset:")
print(data)
meanv <- mean(data)
print(paste("Mean=",meanv))
medianv <- median(data)
print(paste("Median=",medianv))
mode_funtion <- function(x){
  unq_values <- unique(x)
  unq_values[which.max(tabulate(match(x,unq_values)))]
}
modev <- mode_funtion(data)
print(paste("Mode=",modev))
maxv <- max(data)
print(paste("Maximum=",maxv))
minv <- min(data)
print(paste("Minimum=",minv))
varv <- var(data)
print(paste("Variance=",varv))
sdv <- sd(data)
print(paste("Standard deiation=",sdv))
summary(data)
barplot(data)
hist(data)
pie(data)